<?PHP

/*
* Captcha Image Generator
* 
* the captcha_code is generated by the KIS/CPIS Class and is available via the 
* session variable captcha_code
*/

session_start();

$imgX = 60;
$imgY = 17;
$image = imagecreatetruecolor($imgX, $imgY);

$backgr_col = imagecolorallocate($image, 238,239,239);
$border_col = imagecolorallocate($image, 208,208,208);
$text_col = imagecolorallocate($image, 46,60,31);

imagefilledrectangle($image, 0, 0, $imgX, $imgY, $backgr_col);
imagerectangle($image, 0, 0, ($imgX - 1), ($imgY - 1), $border_col);

$font = "../src/VWhx.ttf"; // it's a Bitstream font check www.gnome.org for more
$font_size = 9;
$angle = 0;
$box = imagettfbbox($font_size, $angle, $font,$_SESSION['captcha_code']);
$x = (int)($imgX - $box[4]) / 2;
$y = (int)($imgY - $box[5].-8) / 2;
imagettftext($image, $font_size, $angle, $x, $y, $text_col, $font, $_SESSION['captcha_code']);

header("Content-type: image/png");
imagepng($image);
imagedestroy ($image);


?>