MIKOS: Mikos Class Reference
Mikos Class Reference
Public Member Functions
Mikos ($username= '', $password= '')
parseWsdlFunctions ()
call ($name, $inputvars=array())
login ($username, $password)
logout ()
requireLogin ()
Public Attributes
$srv = null
$sessionId = ''
$memberId = 0
$custInfo = array()
$functions = array()
$loggedIn = false
Detailed Description
Mikos Applikation
Author:
Henrik Westphal, <hwestphal@nwmgbr.de> Wrapper fuer den PEAR::SOAP Client
Henrik Westphal, <hwestphal@nwmgbr.de> Mikos Applikation
public
Author:
Henrik Westphal, <hwestphal@nwmgbr.de>
Definition at line 34 of file class.Mikos.php.
Member Function Documentation
Mikos::Mikos ($ username = '', $ password = '')
Konstruktor der Klasse, erwartet Usernamen und Passwort als Parameter.
public
Author:
Henrik Westphal, <hwestphal@nwmgbr.de>
Parameters:
string
string
Returns:
void
Definition at line 100 of file class.Mikos.php.
References login(), and parseWsdlFunctions().
Referenced by KIS::KIS().
Mikos::parseWsdlFunctions ()
Short description of method parseWsdlFunctions
public
Author:
Henrik Westphal, <hwestphal@nwmgbr.de>
Returns:
void
Definition at line 123 of file class.Mikos.php.
Referenced by Mikos().
Mikos::call ($ name, $ inputvars = array())
Diese Funktion ist ein Wrapper fuer die execFunction-Funktion der Hilft den sessionId-Parameter einzufuegen falls dieser nicht angegeben und prueft die Server-Antwort ob die sessionId noch gueltig ist.
public
Author:
Henrik Westphal, <hwestphal@nwmgbr.de>
Parameters:
string
array
Returns:
void
Definition at line 168 of file class.Mikos.php.
References logout().
Referenced by login().
Mikos::login ($ username, $ password)
Meldet einen User am Server an.
public
Author:
Henrik Westphal, <hwestphal@nwmgbr.de>
Parameters:
string
string
Returns:
boolean
Reimplemented in KIS.
Definition at line 239 of file class.Mikos.php.
References call().
Referenced by Mikos().
Mikos::logout ()
Meldet einen User am Server ab (es wird nur die Session-ID geloescht).
public
Author:
Henrik Westphal, <hwestphal@nwmgbr.de>
Returns:
void
Definition at line 269 of file class.Mikos.php.
Referenced by call().
Mikos::requireLogin ()
Prueft $this->loggedIn, wenn false wird per Header-Redirect auf die verwiesen
public
Author:
Henrik Westphal, <hwestphal@nwmgbr.de>
Returns:
void
Definition at line 287 of file class.Mikos.php.
The documentation for this class was generated from the following file:
/Werkbank/Projekte/VW Club MIKOS neu/htdocs/soapclient/libs/class.Mikos.php